SensorApp/SensorApp/Models/DatabaseContext.cs
using Microsoft.EntityFrameworkCore;

namespace SensorApp.Models
{
    public class DatabaseContext : DbContext
    {
        public DatabaseContext(DbContextOptions<DatabaseContext> options) : base(options) 
        {
        }
        public DbSet<User> Users { get; set; }
        public DbSet<Region> Regions { get; set; }
        public DbSet<Sensor> Sensors { get; set; }
        public DbSet<Indication> Indications { get; set; }
    }
}

SensorApp/SensorApp/Models/Indication.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SensorApp.Models
{
    [Table("indication")]
    public class Indication
    {
        [Key]
        public int Id { get; set; }
        public int Id_Sensor { get; set; }
        public DateTime Date_Indication { get; set; }
        public TimeSpan Time_Indication { get; set; }
        public double Temperature { get; set; }
    }
}

SensorApp/SensorApp/Models/Region.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SensorApp.Models
{
    [Table("region")]
    public class Region
    {
        [Key]
        public int Id { get; set; } 
        public string Name { get; set; } 
    }
}

SensorApp/SensorApp/Models/Sensor.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SensorApp.Models
{
    [Table("sensor")]
    public class Sensor
    {
        [Key]
        public int Id { get; set; }
        public int Id_Region { get; set; }
        public string Name { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }

    }
}

SensorApp/SensorApp/Models/User.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SensorApp.Models
{
    [Table("user")]
    public class User
    {
        [Key]
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Mail { get; set; }
    }
}

SensorApp/SensorApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace SensorApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

SensorApp/SensorApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SensorApp.Models;

namespace SensorApp.Pages
{
    public class IndexModel : PageModel
    {
        /*private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }*/

        /*string reg;
        public string DisplayReg { get; set; }*/
        private DatabaseContext db;
        public IndexModel(DatabaseContext _db)
        {
            db = _db;
        }

        public List<User> Users { get; set; }
       

        public void OnGet()
        {
            //DisplayReg = reg;
            Users = db.Users.ToList();
            

        }

        public void OnPostPrint()
        {
            Mail.sendEmail();
        }
    }
}

SensorApp/SensorApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SensorApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

SensorApp/SensorApp/Pages/TablePages/TableIndications.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using FusionCharts.DataEngine;
using FusionCharts.Visualization;
using SensorApp.Models;
using System.Data;

namespace SensorApp.Pages.TablePages
{
    public class TableIndicationsModel : PageModel
    {
        private DatabaseContext db;
        public TableIndicationsModel(DatabaseContext _db)
        {
            db = _db;
        }

        public List<Indication> Indications { get; set; }
        public List<Sensor> Sensors { get; set; }
        public string ChartJson { get; internal set; }
        public void OnGet()
        {
            Indications = db.Indications.ToList();
            Sensors = db.Sensors.ToList();

            DataTable ChartData = new DataTable();
            ChartData.Columns.Add("Sensor", typeof(System.String));
            ChartData.Columns.Add("Temperature", typeof(System.Double));

            TimeSpan Interval = new TimeSpan(10, 0, 0);
            foreach(var indication in Indications)
            {
                if(indication.Time_Indication == Interval)
                {
                    foreach(var sensor in Sensors)
                    {
                        if (indication.Id_Sensor == sensor.Id)
                        {
                            ChartData.Rows.Add(sensor.Name, indication.Temperature);
                        }
                    }
                }
            }
            StaticSource source = new StaticSource(ChartData);
            DataModel model = new DataModel();
            model.DataSources.Add(source);
            Charts.ColumnChart column = new Charts.ColumnChart("first_chart");
            column.Width.Pixel(700);
            column.Height.Pixel(400);
            column.Data.Source = model;
            column.Caption.Text = "Temperature on Belarus";
            column.SubCaption.Text = "23.09.2023 10:00:00";
            column.Legend.Show = false;
            column.XAxis.Text = "Sensor";
            column.YAxis.Text = "Temperature";
            column.ThemeName = FusionChartsTheme.ThemeName.FUSION;
            ChartJson = column.Render();
        }
    }
}

SensorApp/SensorApp/Pages/TablePages/TableRegions.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SensorApp.Models;

namespace SensorApp.Pages.TablePages
{
    public class TableRegionsModel : PageModel
    {
		private DatabaseContext db;
		public TableRegionsModel(DatabaseContext _db)
		{
			db = _db;
		}

		public List<Region> Regions { get; set; }
		public void OnGet()
        {
			Regions = db.Regions.ToList();
		}

    }
}

SensorApp/SensorApp/Pages/TablePages/TableSensors.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SensorApp.Models;

namespace SensorApp.Pages.TablePages
{
    public class TableSensorsModel : PageModel
    {
		private DatabaseContext db;
		public TableSensorsModel(DatabaseContext _db)
		{
			db = _db;
		}

		public List<Sensor> Sensors { get; set; }
        public List<Region> Regions { get; set; }

        public void OnGet()
        {
			Sensors = db.Sensors.ToList();
			Regions = db.Regions.ToList();
		}
    }
}

SensorApp/SensorApp/Pages/UserOperationPages/LogIn.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SensorApp.Pages.UserOperationPages
{
    public class LogInModel : PageModel
    {
        public void OnGet()
        {

        }
        public void OnPost() 
        {
            
        }


    }
}

SensorApp/SensorApp/Pages/UserOperationPages/SingUp.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SensorApp.Pages.UserOperationPages
{
    public class SingUpModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

SensorApp/SensorApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h2>Users</h2>
    <table>
        <tr>
            <th>Id</th>
            <th>Login</th>
            <th>Password</th>
            <th>Email</th>
        </tr>
        @foreach (var user in Model.Users)
        {
            <tr>
                <td>@user.Id</td>
                <td>@user.Login</td>
                <td>@user.Password</td>
                <td>@user.Mail</td>
            </tr>
        }
    </table>
    
    
    <form asp-page-handler="Print" method="post">
        <button onserverclick="buttonClick" runat="server" id="button1">Send email</button>
    </form>
</div>

    

SensorApp/SensorApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SensorApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SensorApp.styles.css" asp-append-version="true" />
    <link rel="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" type="text/css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">SensorApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/TablePages/TableRegions">Regions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/TablePages/TableSensors">Sensors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/TablePages/TableIndications">Indications</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/UserOperationPages/SingUp">Sing Up</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/UserOperationPages/LogIn">Log In</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SensorApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js" type="text/javascript"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.2.2/Chart.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SensorApp/SensorApp/Pages/TablePages/TableIndications.cshtml
@page
@model SensorApp.Pages.TablePages.TableIndicationsModel
@{
	ViewData["Title"] = "Indications";
}

<script src="//cdn.fusioncharts.com/fusioncharts/latest/fusioncharts.js"></script>

<script src="//cdn.fusioncharts.com/fusioncharts/latest/themes/fusioncharts.theme.fusion.js"></script>

<div class="text-center">
    <h2>Indications</h2>
    <div>@Html.Raw(Model.ChartJson)</div>
    <table class="table table-striped">
        <tr>
            <th>Id</th>
            <th>Sensor</th>
            <th>Date</th>
            <th>Time</th>
            <th>Temperature</th>
        </tr>
        @foreach (var indication in Model.Indications)
        {
            <tr>
                <td>@indication.Id</td>
                @foreach(var sensor in Model.Sensors)
                {
                    if(indication.Id_Sensor == sensor.Id)
                    {
                        <td>@sensor.Name</td>
                    }
                }
                <td>@indication.Date_Indication.ToString("d")</td>
                <td>@indication.Time_Indication</td>
                <td>@indication.Temperature</td>
            </tr>
        }
    </table>
</div>

SensorApp/SensorApp/Pages/TablePages/TableRegions.cshtml
@page
@model SensorApp.Pages.TablePages.TableRegionsModel
@{
	ViewData["Title"] = "Regions";
}

<div class="text-center">
	<h2>Regions</h2>
    <table class="table table-striped">
        <tr>
            <th>Id</th>
            <th>Name</th>
        </tr>
        @foreach (var region in Model.Regions)
        {
            <tr>
                <td>@region.Id</td>
                <td>@region.Name</td>
            </tr>
        }
    </table>
</div>

SensorApp/SensorApp/Pages/TablePages/TableSensors.cshtml
@page
@model SensorApp.Pages.TablePages.TableSensorsModel
@{
	ViewData["Title"] = "Sensors";
}

<div class="text-center">
	<h2>Sensors</h2>
    <table class="table table-striped">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Region</th>
            <th>Latitude</th>
            <th>Longitude</th>
        </tr>
        @foreach (var sensor in Model.Sensors)
        {
            <tr>
                <td>@sensor.Id</td>
                <td>@sensor.Name</td>
                @foreach(var region in Model.Regions)
                {
                    if(sensor.Id_Region == region.Id)
                    {
                        <td>@region.Name</td>
                    }
                }
                <td>@sensor.Latitude</td>
                <td>@sensor.Longitude</td>
            </tr>
        }
    </table>
</div>

SensorApp/SensorApp/Pages/UserOperationPages/LogIn.cshtml
@page
@model SensorApp.Pages.UserOperationPages.LogInModel
@{
	ViewData["Title"] = "LogIn";
}

<div class="text-center">
	<h2>Log In</h2>
	<form method="post">
		<div>
			<lable for="login">Login</lable>
			<input type="text" name="login" placeholder="Login" autofocus required />
		</div>
		<div>
			<lable for="password">Password</lable>
			<input type="password" name="password" placeholder="Password" required />
		</div>
		<input type="submit"/>
	</form>
</div>

SensorApp/SensorApp/Pages/UserOperationPages/SingUp.cshtml
@page
@model SensorApp.Pages.UserOperationPages.SingUpModel
@{
	ViewData["Title"] = "SingUp";
}

<div class="text-center">
	<h2>Sing Up</h2>
	<form>
		<div >
			<lable for="login">Login</lable>
			<input type="text" name="login" placeholder="Login" autofocus required />
		</div>
		<div>
			<lable for="password">Password</lable>
			<input type="password" name="password" placeholder="Password" required />
		</div>
		<div>
			<lable for="mail">Email</lable>
			<input type="email" name="mail" placeholder="email" required />
		</div>
		<input type="submit"/>
	</form>
</div>